#деплой при создании новой версии

name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Pull image
        run: docker pull alexkos58/cep-core:${{ steps.get_tag.outputs.tag }}

      - name: Print image info
        run: |
          echo "Деплой версии: ${{ steps.get_tag.outputs.tag }}"
          echo "Образ: alexkos58/cep-core:${{ steps.get_tag.outputs.tag }}"

      - name: Done
        run: echo "Проект запущен и обновлён успешно"
