#деплой при создании новой версии
name: CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t alexkos58/cep-core:latest .
          docker push alexkos58/cep-core:latest

      - name: Get image tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Print image info
        run: |
          echo "Деплой версии: ${{ steps.get_tag.outputs.tag }}"
          echo "Образ: alexkos58/cep-core:${{ steps.get_tag.outputs.tag }}"

      - name: Pull image
        run: docker pull alexkos58/cep-core:${{ steps.get_tag.outputs.tag }}

      - name: Done
        run: echo "Проект запущен и обновлён успешно"
